apiVersion: apps/v1 
kind: Deployment
metadata:
  name: project1-deployment
  labels: 
     app: project1

spec:
  replicas: 3 
  selector:
    matchLabels:
      app: project1

  template:
    metadata:
      labels:
        app: project1
    spec:
      containers:
      - name: project1
        image: ebiecas/project1-tomcat
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1