apiVersion: v1
kind: Service
metadata:
  name: project1-service
  labels:
    app: project1
spec:
  selector:
    app: project1 

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer