# Pull tomcat latest image from dockerhub 
From tomcat:latest

# Maintainer
# www.github.com/ebiecas02/
MAINTAINER "Ebrahim Cassim" 

# copy war file on to container 
COPY ./XYZtechnologies-1.0.war /usr/local/tomcat/webapps